apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8deploy
  name: k8deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: k8deploy
status:
  loadBalancer: {}
